server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dynamicsum
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple

logging:
  level:
    root: INFO

